language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make

  - os: linux
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      packages:
        - clang-9
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make
